### ISSUE TITLE
Hacer andar el docker-compose para dev

### ISSUE THREAD

**Issue by jperelli** [cualbondi/cualbondi#2]
Parece que no esta funcionando bien el env de dev con docker-compose

 - Eliminar cualquier sysctl (no funcionan en mac)
 - Correr web y api directamente con `manage.py runserver`
 - Autoconfigurar el front para usar esa api en otro port desde una variable de env
 - no meter sentry en dev
 - renombrar `docker-compose.dev.yml` a `docker-compose.yml`

**Comment by marcosfede** [comment]
work in progress in #1 . cuales configs del .dev irian en ese file? ej: volumenes nombrados o montar un dir local

**Comment by jperelli** [comment]
supongo que las de postgres user pass db, creo que no necesita nada mas por ahora, lo meteria directamente hardcodeado (sin que el dev use el archivo .env)

con lo de los volumenes, usa la que te parezca mejor, me falta estudiar mejor eso
